package com.tyyj.db.Entities;
// Generated 2016-1-25 22:30:35 by Hibernate Tools 3.4.0.CR1

/**
 * Table1 generated by hbm2java
 */
public class Table1 implements java.io.Serializable {

	private int id;
	private String name;

	public Table1() {
	}

	public Table1(int id) {
		this.id = id;
	}

	public Table1(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
