package com.tyyj.db.Entities;
// Generated 2016-1-26 23:21:05 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * TyyjActivity generated by hbm2java
 */

@Entity(name="tyyj_activity")
public class TyyjActivity implements java.io.Serializable {

	@Id
	@Column(name="id",unique=true,length=50,nullable=false)
	@GenericGenerator(name="system-uuid",strategy="uuid.hex")
	@GeneratedValue(generator="system-uuid")
	private String id;
	
	@Column(name="name",length=100, nullable=false)
	private String name;
	
	@ManyToOne(cascade=CascadeType.ALL,targetEntity=TyyjManor.class)
	//@Column(name="manor_id")
	private TyyjManor manor;
	
	@Column(name="join_count_limit", length=3, columnDefinition="INT default 1")
	private Integer joinCountLimit;
	
	@Temporal(TemporalType.DATE)
	@Column(name="validity")
	private Date validity;
	
	@Column(name="activity_type", length=3, columnDefinition="INT default 1")
	private Integer activityType;
	
	@Column(name="key_words", length=100)
	private String keyWords;
	
	@Column(name="discription", length=200)
	private String discription;
	
	@Column(name="unit_prise")
	private Double unitPrise;
	
	
	@Column(name="join_ways", length=20)
	private String joinWays;

	@Column(name="acvivity_status", length = 2)
	private int activityStatus;
	
	
	public TyyjActivity() {
	}

	public TyyjActivity(String id) {
		this.id = id;
	}

	public TyyjActivity(String id, String name, TyyjManor manor, Integer joinCountLimit, Date validity,
			Integer activityType, String keyWords, String discription, Double unitPrise, String joinWays) {
		this.id = id;
		this.name = name;
		this.manor = manor;
		this.joinCountLimit = joinCountLimit;
		this.validity = validity;
		this.activityType = activityType;
		this.keyWords = keyWords;
		this.discription = discription;
		this.unitPrise = unitPrise;
		this.joinWays = joinWays;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getJoinCountLimit() {
		return this.joinCountLimit;
	}

	public void setJoinCountLimit(Integer joinCountLimit) {
		this.joinCountLimit = joinCountLimit;
	}

	public Date getValidity() {
		return this.validity;
	}

	public void setValidity(Date validity) {
		this.validity = validity;
	}

	public Integer getActivityType() {
		return this.activityType;
	}

	public void setActivityType(Integer activityType) {
		this.activityType = activityType;
	}

	public String getKeyWords() {
		return this.keyWords;
	}

	public void setKeyWords(String keyWords) {
		this.keyWords = keyWords;
	}

	public String getDiscription() {
		return this.discription;
	}

	public void setDiscription(String discription) {
		this.discription = discription;
	}

	public Double getUnitPrise() {
		return this.unitPrise;
	}

	public void setUnitPrise(Double unitPrise) {
		this.unitPrise = unitPrise;
	}

	public TyyjManor getManor() {
		return manor;
	}

	public void setManor(TyyjManor manor) {
		this.manor = manor;
	}

	public String getJoinWays() {
		return joinWays;
	}

	public void setJoinWays(String joinWays) {
		this.joinWays = joinWays;
	}

	public int getActivityStatus() {
		return activityStatus;
	}

	public void setActivityStatus(int activityStatus) {
		this.activityStatus = activityStatus;
	}

}
