package com.tyyj.db.Entities;
// Generated 2016-1-26 23:21:05 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TyyjUser generated by hbm2java
 */

@Entity(name="tyyj_user")
public class TyyjUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1649371246005211100L;

	@Id
	@Column(name="id",unique=true,length=50,nullable=false)
	@GenericGenerator(name="system-uuid",strategy="uuid.hex")
	@GeneratedValue(generator="system-uuid")
	private String id;
	
	@Column(name="name", nullable=true, length=45,unique=false)
	private String name;
	
	@Column(name="user_name", nullable=false, length=45,unique=true)
	private String userName;
	
	@Column(name="phone_number", nullable=true, length=45,unique=false)
	private String phoneNumber;
	
	@Column(name="password", nullable=false, length=45,unique=false)
	private String password;

	public TyyjUser() {
	}

	public TyyjUser(String id) {
		this.id = id;
	}

	public TyyjUser(String id, String name, String userName, String phoneNumber, String password) {
		this.id = id;
		this.name = name;
		this.userName = userName;
		this.phoneNumber = phoneNumber;
		this.password = password;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
